/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package building_management;

import static building_management.signin.img;
import com.sun.corba.se.impl.logging.ORBUtilSystemException;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.DecimalFormat;
import java.text.Format;
import java.text.SimpleDateFormat;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.*;

/**
 *
 * @author masdar
 */
public class add_reference extends javax.swing.JFrame {

    /**
     * Creates new form referencies
     * @param bldno
     */
    String[] fields = {"vendor_id", "quantity", "price", "total_price", "date_", "reference_id","buildno","notice","currency_factor"};
    String tableName = "rec_references";
    String tableKey = "re_id";
    String resultquery = "";
  int reference_id=0;
    JFrame invoke ;
    String bldno,bld_desc,refrence_type_id,refrence_type_dsec;
    connect conn;
    DecimalFormat df;
    double currency_factor= 1.0;
    public add_reference(javax.swing.JFrame mainFram,String bldno,String bld_desc,int reference_id,String refrence_type_id,String refrence_type_dsec) throws SQLException {
        invoke =mainFram;
        invoke.setEnabled(false);
        conn = new connect();
        conn.newConnection();

         df= new DecimalFormat("#.####");
        initComponents();
        img = Toolkit.getDefaultToolkit().getImage(java.net.URLClassLoader.getSystemResource("icons/1.png"));

        Dimension screenSize = Toolkit.getDefaultToolkit().getScreenSize();
        int temp_width = (int) screenSize.getWidth();
        int temp_height = (int) screenSize.getHeight();
        // this.setMaximumSize(new Dimension(505, 165));
        this.setSize(750, 190);
        this.setLocation((temp_width - 750) / 2, (temp_height - 190) / 2);
        this.setIconImage(img);
        this.bldno=bldno;
        this.bld_desc=bld_desc;
        this.refrence_type_id=refrence_type_id;
        this.refrence_type_dsec=refrence_type_dsec;
        conn.fillComboBoxWithCondition("references_", "desc_","category_id", customersComboBox,Integer.valueOf(refrence_type_id));
        conn.fillComboBox("vendors", "vendor_name", vendorComboBox1);
        this.setTitle("اضافة احضار للمحضر رقم  "+bld_desc);
        
        bldlbl.setText(bld_desc);
        bldlbl1.setText(refrence_type_dsec);
        customersComboBox.grabFocus();
        
        if(conn.isCategorInDollar(refrence_type_id))
        {
            currency_factor=Double.valueOf(connect.dollar_factor_value);
        }  
        resultquery = "SELECT "
            + " rec_references.notice as " + '"' + "ملاحظات" + '"'
             + ", vendors.vendor_name as " + '"' + "المورد" + '"'
            + ", rec_references.date_ as " + '"' + "التاريخ" + '"'
            + ", rec_references.total_price as " + '"' + "الاجمالي" + '"'
            + ", rec_references.price as " + '"' + "السعر" + '"'
            + ", rec_references.quantity  as " + '"' + "الكمية" + '"'
            + ", references_.desc_  as " + '"' + "الاحضار" + '"'
            + " FROM rec_references  "
            + "   left join references_ on rec_references.reference_id=references_.reference_id "
            + "   left join vendors on rec_references.vendor_id=vendors.vendor_id "
            + " where re_id = ";
                
         if(reference_id>0)
        {
            
            getReferenceInfos(reference_id);
            
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        customersComboBox = new javax.swing.JComboBox();
        jLabel5 = new javax.swing.JLabel();
        priceTextField = new javax.swing.JTextField();
        inDate = new com.toedter.calendar.JDateChooser();
        jLabel14 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        savein = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        noticeTextField = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        quantity = new javax.swing.JTextField();
        totalextField = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        vendorComboBox1 = new javax.swing.JComboBox();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        bldlbl1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        bldlbl = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
        });

        customersComboBox.setNextFocusableComponent(customersComboBox);
        customersComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                customersComboBoxActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("السعر");

        priceTextField.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        priceTextField.setNextFocusableComponent(noticeTextField);
        priceTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                priceTextFieldActionPerformed(evt);
            }
        });
        priceTextField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                priceTextFieldKeyReleased(evt);
            }
        });

        inDate.setDateFormatString("MMM d, yyyy ");
        inDate.setNextFocusableComponent(quantity);

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel14.setText("التاريخ");

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("الاحضار");

        savein.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        savein.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/Files-New-File-icon 24.png"))); // NOI18N
        savein.setText("حفظ");
        savein.setMargin(new java.awt.Insets(2, 2, 2, 2));
        savein.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveinActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("ملاحظة");

        noticeTextField.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        noticeTextField.setNextFocusableComponent(savein);
        noticeTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                noticeTextFieldActionPerformed(evt);
            }
        });
        noticeTextField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                noticeTextFieldKeyReleased(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("المورد");

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("الكمية");

        quantity.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        quantity.setNextFocusableComponent(priceTextField);
        quantity.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                quantityActionPerformed(evt);
            }
        });
        quantity.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                quantityKeyReleased(evt);
            }
        });

        totalextField.setEditable(false);
        totalextField.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        totalextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                totalextFieldActionPerformed(evt);
            }
        });
        totalextField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                totalextFieldKeyReleased(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("الاجمالي");

        vendorComboBox1.setNextFocusableComponent(inDate);
        vendorComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                vendorComboBox1ActionPerformed(evt);
            }
        });

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/math-add-icon16.png"))); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/math-add-icon16.png"))); // NOI18N
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(savein)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGap(0, 10, Short.MAX_VALUE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(totalextField)
                                    .addComponent(inDate, javax.swing.GroupLayout.DEFAULT_SIZE, 112, Short.MAX_VALUE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(83, 83, 83))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(vendorComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(priceTextField, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(59, 59, 59))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
                                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(quantity, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(customersComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel6))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(noticeTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 560, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(inDate, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(customersComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel14)
                            .addComponent(vendorComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(quantity, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(priceTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(totalextField, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(savein, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(noticeTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(7, 7, 7))
        );

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText("إضافة  احضار : ");

        bldlbl1.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        bldlbl1.setForeground(new java.awt.Color(51, 51, 255));
        bldlbl1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("للمحضر");

        bldlbl.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        bldlbl.setForeground(new java.awt.Color(51, 51, 255));
        bldlbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(bldlbl, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(bldlbl1, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addGap(131, 131, 131))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(bldlbl1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel2)
                    .addComponent(bldlbl, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        invoke.setEnabled(true);
        invoke.toFront();
    }//GEN-LAST:event_formWindowClosed

    private void customersComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_customersComboBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_customersComboBoxActionPerformed

    private void priceTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_priceTextFieldActionPerformed

    }//GEN-LAST:event_priceTextFieldActionPerformed

    private void priceTextFieldKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_priceTextFieldKeyReleased

     calcTotal();
    }//GEN-LAST:event_priceTextFieldKeyReleased

    private void saveinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveinActionPerformed

        try {

            Boolean status=true;
            if(reference_id>0)
            {
                status= UpdateRecord();
            }else
            {
               status=  SaveInRecord();
            }
if(status)
            this.dispose();

        } catch (SQLException ex) {
            Logger.getLogger(GUI.class.getName()).log(Level.SEVERE, null, ex);
        } catch (NullPointerException ex) {
            customersComboBox.setBackground(Color.red);
        }
    }//GEN-LAST:event_saveinActionPerformed

    private void noticeTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_noticeTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_noticeTextFieldActionPerformed

    private void noticeTextFieldKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_noticeTextFieldKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_noticeTextFieldKeyReleased

    private void quantityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_quantityActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_quantityActionPerformed

    private void quantityKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_quantityKeyReleased
        calcTotal();
    }//GEN-LAST:event_quantityKeyReleased

    private void totalextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_totalextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_totalextFieldActionPerformed

    private void totalextFieldKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_totalextFieldKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_totalextFieldKeyReleased

    private void vendorComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_vendorComboBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_vendorComboBox1ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
       try{ 
           
              new referenciesSubTypes(this).setVisible(true);
          
          }catch(SQLException e)
          {
              
          }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        try{ 
              new addvendor(this,"0").setVisible(true);
          
          }catch(SQLException e)
          {
              
          }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        try {
            String reference=customersComboBox.getSelectedItem().toString();
            String vendor=vendorComboBox1.getSelectedItem().toString();
            conn.fillComboBoxWithCondition("references_", "desc_","category_id", customersComboBox,Integer.valueOf(refrence_type_id));
            conn.fillComboBox("vendors", "vendor_name", vendorComboBox1);
            customersComboBox.setSelectedItem(reference);
            vendorComboBox1.setSelectedItem(vendor);
            
             }catch(SQLException e)
          {
              
          }
    }//GEN-LAST:event_formWindowActivated

 

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel bldlbl;
    private javax.swing.JLabel bldlbl1;
    private javax.swing.JComboBox customersComboBox;
    private com.toedter.calendar.JDateChooser inDate;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField noticeTextField;
    private javax.swing.JTextField priceTextField;
    private javax.swing.JTextField quantity;
    private javax.swing.JButton savein;
    private javax.swing.JTextField totalextField;
    private javax.swing.JComboBox vendorComboBox1;
    // End of variables declaration//GEN-END:variables

    
      private Boolean SaveInRecord() throws SQLException {

        quantity.setBackground(Color.white);
        priceTextField.setBackground(Color.white);
        totalextField.setBackground(Color.white);
        
        if (!Functions.validation(quantity.getText(), 2, true)) {
            quantity.setBackground(Color.red);
            quantity.grabFocus();
            quantity.selectAll();
            
            return false;
        }
        if (!Functions.validation(priceTextField.getText(), 2, true)) {
            priceTextField.setBackground(Color.red);
            priceTextField.grabFocus();
            priceTextField.selectAll(); 
            
            return false;
        }
        if (!Functions.validation(totalextField.getText(), 2, true)) {
            totalextField.setBackground(Color.red);
            totalextField.grabFocus();
            totalextField.selectAll(); 
            
            return false;
        }
        
        Format formatter;

        formatter = new SimpleDateFormat("yyyy-MM-dd");
        String recorindDate = "";
        try {
            recorindDate = formatter.format(inDate.getCalendar().getTime());
        } catch (NullPointerException te) {
            recorindDate = null;
            inDate.grabFocus();
            inDate.setBackground(Color.red);
            
            return false;

        }

        int reference_id = conn.getIDByDesc("references_", customersComboBox.getSelectedItem().toString(), "desc_", "reference_id");
        int vendor_id = conn.getIDByDesc("vendors", vendorComboBox1.getSelectedItem().toString(), "vendor_name", "vendor_id");
        
        String quantity_ = quantity.getText();
        String price = priceTextField.getText();
        String totale = totalextField.getText();
        
       
       //"vendor_id", "quantity", "price", "total_price", "date_", "reference_id","buildno","notice"

        String[] values = {
            "'" + vendor_id + "'",
            "'" + quantity_ + "'",
            "'" + price + "'",
            "'" + totale + "'",
            "'" + recorindDate + "'",
            "'" + reference_id + "'",
            "'" + bldno + "'",
            "'" + noticeTextField.getText() + "'",
            "'" + currency_factor + "'"
        };
        conn.insertIntoTable(tableName, fields, values);
        
return true;
    }
     private Boolean UpdateRecord() throws SQLException {

        quantity.setBackground(Color.white);
        priceTextField.setBackground(Color.white);
        totalextField.setBackground(Color.white);
        
        if (!Functions.validation(quantity.getText(), 2, true)) {
            quantity.setBackground(Color.red);
            quantity.grabFocus();
            quantity.selectAll();
            
            return false;
        }
        if (!Functions.validation(priceTextField.getText(), 2, true)) {
            priceTextField.setBackground(Color.red);
            priceTextField.grabFocus();
            priceTextField.selectAll(); 
            
            return false;
        }
        if (!Functions.validation(totalextField.getText(), 2, true)) {
            totalextField.setBackground(Color.red);
            totalextField.grabFocus();
            totalextField.selectAll(); 
            
            return false;
        }
        
        Format formatter;

        formatter = new SimpleDateFormat("yyyy-MM-dd");
        String recorindDate = "";
        try {
            recorindDate = formatter.format(inDate.getCalendar().getTime());
        } catch (NullPointerException te) {
            recorindDate = null;
            inDate.grabFocus();
            inDate.setBackground(Color.red);
            
            return false;

        }

        int referenc_id = conn.getIDByDesc("references_", customersComboBox.getSelectedItem().toString(), "desc_", "reference_id");
        int vendor_id = conn.getIDByDesc("vendors", vendorComboBox1.getSelectedItem().toString(), "vendor_name", "vendor_id");
        
        String quantity_ = quantity.getText();
        String price = priceTextField.getText();
        String totale = totalextField.getText();
        
       
       //{"vendor_id", "quantity", "price", "total_price", "date_", "reference_id","buildno","notice","currency_factor"};
   
        String[] values = {
            "'" + vendor_id + "'",
            "'" + quantity_ + "'",
            "'" + price + "'",
            "'" + totale + "'",
            "'" + recorindDate + "'",
            "'" + referenc_id + "'",
            "'" + bldno + "'",
            "'" + noticeTextField.getText() + "'",
            "'" + currency_factor + "'"
        };
        conn.updateTable(tableName, fields, values,tableKey,""+reference_id);
        
return true;
    }

    
    private void getReferenceInfos(int reference_id) {
      this.reference_id=reference_id;
       this.setTitle("تعديل احضار للمحضر "+bld_desc);
      jLabel3.setText("تعديل احضار :");
        try{
          String query=resultquery+ reference_id;
         
         System.out.println(query);
            Statement recordsStmt = conn.conn.createStatement();
            ResultSet recordsResultSet = recordsStmt.executeQuery(query);
     
          while (recordsResultSet.next()) {

              noticeTextField.setText(recordsResultSet.getString(1));
              vendorComboBox1.setSelectedItem(recordsResultSet.getString(2));
              inDate.setDate(Functions.StringToDate(recordsResultSet.getString(3)));
              totalextField.setText(recordsResultSet.getString(4));
              priceTextField.setText(recordsResultSet.getString(5));
              quantity.setText(recordsResultSet.getString(6));
              customersComboBox.setSelectedItem(recordsResultSet.getString(7));
              
              
                          }
        } catch (SQLException ex) {
            Logger.getLogger(addpayment.class.getName()).log(Level.SEVERE, null, ex);
        } 
    }

    private void calcTotal() {
           Double price,weight;
         if (!Functions.validation(priceTextField.getText(), 2, true)) {
            price=0.0;
        }
         else 
         {
             price=Double.parseDouble(priceTextField.getText());
         }
        if (!Functions.validation(quantity.getText(), 2, true)) {
            weight=0.0;

        }else{
           weight= Double.parseDouble(quantity.getText());
        }
        
        Double Total=price*weight;
                totalextField.setText(df.format(Total));
    }

   
 
}
