/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package building_management;

import static building_management.signin.img;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.*;

/**
 *
 * @author masdar
 */
public class elements extends javax.swing.JFrame {

    /**
     * Creates new form elements
     * @param bldno
     */
    String[] fields = { "quantity", "price", "total_price", "date_", "element_id","worker_id","buildno","notice"};
    String tableName = "rec_elements";
    String tableKey = "re_id";
    String resultquery = "SELECT "
            + " rec_elements.notice as " + '"' + "ملاحظات" + '"'
            + ", rec_elements.date_ as " + '"' + "التاريخ" + '"'
            + ", rec_elements.total_price as " + '"' + "الاجمالي" + '"'
            + ", rec_elements.price as " + '"' + "السعر" + '"'
            + ", units.desc_  as " + '"' + "الواحدة" + '"'
            + ", rec_elements.quantity  as " + '"' + "الكمية" + '"'
            + ", workers.worker_name  as " + '"' + "المهني" + '"'
            + ", elements_.desc_  as " + '"' + "بيان العمل" + '"'
             
            + " FROM rec_elements  "
            + " left  join elements_ on rec_elements.element_id=elements_.element_id "
            + " left join units on units.id_ =elements_.unit_id "
            + " left  join workers on workers.worker_id = rec_elements.worker_id "
           
            + "   where rec_elements.buildno=";
    
    JFrame invoke ;
    String bldno,bld_desc;
    String element_type_id,element_type_dsec;
    connect conn;
    public elements(javax.swing.JFrame mainFram,String bldno,String bld_desc,String element_type_id,String element_type_dsec) throws SQLException {
        invoke =mainFram;
        invoke.setEnabled(false);
        conn = new connect();
        conn.newConnection();

        initComponents();
        img = Toolkit.getDefaultToolkit().getImage(java.net.URLClassLoader.getSystemResource("icons/1.png"));

        Dimension screenSize = Toolkit.getDefaultToolkit().getScreenSize();
        int temp_width = (int) screenSize.getWidth();
        int temp_height = (int) screenSize.getHeight();
        // this.setMaximumSize(new Dimension(505, 165));
        this.setSize(761, 700);
        this.setLocation((temp_width - 761) / 2, (temp_height - 700) / 2);
        this.setIconImage(img);
        this.bldno=bldno;
        this.bld_desc=bld_desc;
        this.element_type_id=element_type_id;
        this.element_type_dsec=element_type_dsec;
        this.setTitle(bld_desc); 
        bldlbl.setText(bld_desc);
        bldlbl1.setText(element_type_dsec);
        resultquery=resultquery+bldno+" and rec_elements.element_id= '"+element_type_id+"' ";
        ShowResuls();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        bldlbl = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        inputsRecordsjTable = new javax.swing.JTable();
        editSelected = new javax.swing.JButton();
        deleteselected = new javax.swing.JButton();
        add = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        bldlbl1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        searchjTextField1 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("قائمة أعمال ");

        bldlbl.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        bldlbl.setForeground(new java.awt.Color(51, 51, 255));
        bldlbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        jScrollPane2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        inputsRecordsjTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                inputsRecordsjTableMouseClicked(evt);
            }
        });
        inputsRecordsjTable.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                inputsRecordsjTableKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                inputsRecordsjTableKeyReleased(evt);
            }
        });
        jScrollPane2.setViewportView(inputsRecordsjTable);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 626, Short.MAX_VALUE)
        );

        editSelected.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        editSelected.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/edit 32.png"))); // NOI18N
        editSelected.setText("تعديل");
        editSelected.setMargin(new java.awt.Insets(2, 2, 2, 2));
        editSelected.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editSelectedActionPerformed(evt);
            }
        });

        deleteselected.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        deleteselected.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/document-delete-icon24.png"))); // NOI18N
        deleteselected.setText("حذف");
        deleteselected.setMargin(new java.awt.Insets(2, 2, 2, 2));
        deleteselected.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteselectedActionPerformed(evt);
            }
        });

        add.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        add.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/Files-New-File-icon 24.png"))); // NOI18N
        add.setText("اضافة");
        add.setMargin(new java.awt.Insets(2, 2, 2, 2));
        add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("للمحضر");

        bldlbl1.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        bldlbl1.setForeground(new java.awt.Color(51, 51, 255));
        bldlbl1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel3.setText("بحث  :");

        searchjTextField1.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/prev-icon24.png"))); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(108, 108, 108)
                        .addComponent(bldlbl, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(bldlbl1, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel1)
                        .addGap(0, 143, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(deleteselected)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(editSelected)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(add)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(searchjTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel3)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(bldlbl1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 24, Short.MAX_VALUE)
                        .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 24, Short.MAX_VALUE))
                    .addComponent(bldlbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(editSelected, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(deleteselected, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(add, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(searchjTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        invoke.setEnabled(true);
        invoke.toFront();
    }//GEN-LAST:event_formWindowClosed

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
       
            ShowResuls();
         
    }//GEN-LAST:event_formWindowActivated

    private void inputsRecordsjTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_inputsRecordsjTableMouseClicked

    }//GEN-LAST:event_inputsRecordsjTableMouseClicked

    private void inputsRecordsjTableKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_inputsRecordsjTableKeyPressed

    }//GEN-LAST:event_inputsRecordsjTableKeyPressed

    private void inputsRecordsjTableKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_inputsRecordsjTableKeyReleased

    }//GEN-LAST:event_inputsRecordsjTableKeyReleased

    private void editSelectedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editSelectedActionPerformed
        
              try{
                  new add_element(this,bldno,bld_desc,getselectedRecordID(),element_type_id,element_type_dsec).setVisible(true);
            } catch (SQLException ex) {
                Logger.getLogger(referenciesPaymentsDetails.class.getName()).log(Level.SEVERE, null, ex);
            }

    }//GEN-LAST:event_editSelectedActionPerformed

    private int getselectedRecordID()
{
   int  selectedRow = inputsRecordsjTable.getSelectedRow();
        if(selectedRow<0)
        {
            //showMessage("يجب تحديد سطر لحذفه",false);
            return 0;
        }
        
        String refereneName = inputsRecordsjTable.getValueAt(selectedRow, 7).toString();
      
        
        String s_quantity = inputsRecordsjTable.getValueAt(selectedRow, 5).toString();
        String s_price = inputsRecordsjTable.getValueAt(selectedRow, 3).toString();
        String s_total = inputsRecordsjTable.getValueAt(selectedRow, 2).toString();
        String s_date= inputsRecordsjTable.getValueAt(selectedRow, 1).toString();

       
        //if(Functions.deletePrevilege){
            String refer_id = "";

            try {
 int worker_id = conn.getIDByDesc("workers", inputsRecordsjTable.getValueAt(selectedRow, 6).toString(), "worker_name", "worker_id");

                refer_id = conn.searchIdwithcondition("elements_", "element_id", "desc_", refereneName);
                

                String[] values = {
                   
                    "'" + s_quantity + "'",
                    "'" + s_price + "'",
                    "'" + s_total + "'",
                    "'" + s_date + "'",
                    "'" + refer_id + "'",
                    "'" + worker_id + "'",
                    "'" + bldno + "'"};

                String[] fields1 ={ "quantity", "price", "total_price", "date_", "element_id","worker_id","buildno"};


                return conn.getIDByCondiotonArray(tableName, fields1, values,tableKey);

                
            } catch (SQLException ex) {
               return 0;
            }
}
    
    
    private void deleteselectedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteselectedActionPerformed
 
              try {

               
                conn.deleteFromTable(tableName, tableKey, ""+getselectedRecordID());
                ShowResuls();
            } catch (SQLException ex) {
                Logger.getLogger(referenciesPaymentsDetails.class.getName()).log(Level.SEVERE, null, ex);
            }
            //deleteselected.setEnabled(false);
    }//GEN-LAST:event_deleteselectedActionPerformed

    private void addActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addActionPerformed

     try {
         new add_element(this,this.bldno,bld_desc,0,element_type_id,element_type_dsec).setVisible(true);
     }catch (SQLException ex) {
                Logger.getLogger(referenciesPaymentsDetails.class.getName()).log(Level.SEVERE, null, ex);
            }
 
    }//GEN-LAST:event_addActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
               
        String searchtext=searchjTextField1.getText();
        String whereClause = "and (rec_elements.notice like '%" + searchtext + "%'"
        + " or workers.worker_name like '%" + searchtext + "%'"
        + " or elements_.desc_ like '%" + searchtext + "%')  order by rec_elements.date_";

        try {
            System.out.println(resultquery+whereClause);
            conn.QueryTable(resultquery+whereClause, inputsRecordsjTable);
        }catch (NullPointerException ex) {

        }
    }//GEN-LAST:event_jButton1ActionPerformed

 

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton add;
    private javax.swing.JLabel bldlbl;
    private javax.swing.JLabel bldlbl1;
    private javax.swing.JButton deleteselected;
    private javax.swing.JButton editSelected;
    private static javax.swing.JTable inputsRecordsjTable;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField searchjTextField1;
    // End of variables declaration//GEN-END:variables

   
    private void ShowResuls() {
        try {
       
            conn.QueryTable(resultquery+" order by rec_elements.date_ ", inputsRecordsjTable);
        }catch (NullPointerException ex) {
            
        }
            
        
        
       // conn.QueryTable(recordsquery, cardRecordsjTable);
    }
}
