/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package building_management;

import static building_management.signin.img;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.awt.event.ActionEvent;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JButton;
import javax.swing.JFrame;

/**
 *
 * @author masdar
 */
public class GUI extends javax.swing.JFrame {
    

    /**
     * Creates new form GUI
     */
    String bld_dec = "";
        int bld_id = 0;
        JFrame frame ;
     JButton jButton;
     String project_desc;
    JFrame invoke ;
    public GUI(javax.swing.JFrame mainFram,String project_desc) {
        invoke =mainFram;
        invoke.setEnabled(false);
        initComponents();
        frame=this;
        img = Toolkit.getDefaultToolkit().getImage(java.net.URLClassLoader.getSystemResource("icons/1.png"));
        this.project_desc=project_desc;
        Dimension screenSize = Toolkit.getDefaultToolkit().getScreenSize();
        int temp_width = (int) screenSize.getWidth();
        int temp_height = (int) screenSize.getHeight();
        // this.setMaximumSize(new Dimension(505, 165));
        this.setSize(686, 740);
        this.setLocation((temp_width - 686) / 2, (temp_height - 740) / 2);
        this.setIconImage(img);
        this.setTitle("محاضر "+project_desc);
        jButton1.setText("مصاريف  "+project_desc);
        
         addbuldingButtonsToPanel(project_desc);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
        });

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton1.setText("مصاريف ");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jPanel1.setLayout(new java.awt.GridLayout(6, 6));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(267, 267, 267)
                .addComponent(jButton1)
                .addContainerGap(336, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 777, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        try {
            new CategoryOutlaysDetails1(this,this.project_desc).setVisible(true);
        } catch (SQLException ex) {
            Logger.getLogger(totalOutlaysDetails.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
         invoke.setEnabled(true);
        invoke.toFront();
    }//GEN-LAST:event_formWindowClosed

 private void jButtonActionPerformed(ActionEvent evt) {                                         
//      
      new building(this,evt.getActionCommand()).setVisible(true);
    }
 
 private void addbuldingButtonsToPanel(String project_desc)
 {
        connect inConn;
        inConn = new connect();
        inConn.newConnection();
       
        Statement stmt = null;
        
        String query = "SELECT id_, desc_ FROM buildings where category='"+project_desc+"' order by desc_";
        try {
            stmt = inConn.conn.createStatement();
            ResultSet res = stmt.executeQuery(query);
            jPanel1.removeAll();
            while (res.next()) {
                bld_dec = res.getString("desc_");
                bld_id = res.getInt("id_");

                
                jButton = new javax.swing.JButton();
                jButton.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N

                jButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/bld.png"))); // NOI18N

                jButton.setText(bld_dec);

                jButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

                jButton.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);

                jButton.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
                
               
                
                 
           jButton.setActionCommand(bld_id+"");
          
           
                jButton.addActionListener((ActionEvent evt) -> {
                    jButtonActionPerformed(evt);
                });
                
                 jPanel1.add(jButton);
                
       
        

            }

        } catch (SQLException ex) {
            Logger.getLogger(____quantityReport.class.getName()).log(Level.SEVERE, null, ex);
        }

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
