/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package building_management;

import static building_management.signin.img;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.sql.SQLException;
import java.util.HashMap;
import java.util.Map;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.*;

/**
 *
 * @author masdar
 */
public class referencies extends javax.swing.JFrame {

    /**
     * Creates new form referencies
     * @param bldno
     */
    String[] fields = {"vendor_id", "quantity", "price", "total_price", "date_", "reference_id","buildno","notice"};
    String tableName = "rec_references";
    String tableKey = "re_id";
    String resultquery = "";
    String searchTerm="";
    JFrame invoke ;
    String bldno,bld_desc,refrence_type_id,refrence_type_dsec;
    connect conn;
    public referencies(javax.swing.JFrame mainFram,String bldno,String bld_desc,String refrence_type_id,String refrence_type_dsec) throws SQLException {
        invoke =mainFram;
        invoke.setEnabled(false);
        conn = new connect();
        conn.newConnection();
        this.bldno = bldno;
        this.bld_desc = bld_desc;
        this.refrence_type_id = refrence_type_id;
        this.refrence_type_dsec = refrence_type_dsec;
        initComponents();
        img = Toolkit.getDefaultToolkit().getImage(java.net.URLClassLoader.getSystemResource("icons/1.png"));

        Dimension screenSize = Toolkit.getDefaultToolkit().getScreenSize();
        int temp_width = (int) screenSize.getWidth();
        int temp_height = (int) screenSize.getHeight();
        // this.setMaximumSize(new Dimension(505, 165));
        this.setSize(761, 710);
        this.setLocation((temp_width - 761) / 2, (temp_height - 710) / 2);
        this.setIconImage(img);
        
   
        this.setTitle("احضارات "+bld_desc);
        bldlbl.setText(bld_desc);
        bldlbl1.setText(refrence_type_dsec);
        jMenu3.setText("احصائيات "+refrence_type_dsec);
        resultquery = "SELECT "
            + " rec_references.notice as " + '"' + "ملاحظات" + '"'
            + ", vendors.vendor_name as " + '"' + "المورد" + '"'
            + ", rec_references.date_ as " + '"' + "التاريخ" + '"'
            + ", rec_references.total_price as " + '"' + "الاجمالي" + '"'
            + ", rec_references.price as " + '"' + "السعر" + '"'
            + ", units.desc_  as " + '"' + "الواحدة" + '"'
            + ", rec_references.quantity  as " + '"' + "الكمية" + '"'
            + ", references_.desc_  as " + '"' + "الاحضار" + '"'
            +(conn.isCategorInDollar(refrence_type_id)?", rec_references.currency_factor as \"معامل التحويل\"   ":"")
              
            + " FROM rec_references  "
            + " left  join references_ on rec_references.reference_id=references_.reference_id "
            + "  left join references_categories on references_.category_id=references_categories.reference_id "
            + "  left join units on references_categories.unit_id=units.id_  "
            
            + "  left join vendors on rec_references.vendor_id=vendors.vendor_id "
            + " where rec_references.buildno=";
        
        
        resultquery=resultquery+bldno+" and references_.category_id= '"+refrence_type_id+"' ";
        ShowResuls();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        inputsRecordsjTable = new javax.swing.JTable();
        editSelected = new javax.swing.JButton();
        deleteselected = new javax.swing.JButton();
        add = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        bldlbl1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        bldlbl = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        searchjTextField1 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        add1 = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu3 = new javax.swing.JMenu();
        jMenuItem6 = new javax.swing.JMenuItem();
        jMenuItem9 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
        });

        jScrollPane2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        inputsRecordsjTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                inputsRecordsjTableMouseClicked(evt);
            }
        });
        inputsRecordsjTable.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                inputsRecordsjTableKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                inputsRecordsjTableKeyReleased(evt);
            }
        });
        jScrollPane2.setViewportView(inputsRecordsjTable);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 569, Short.MAX_VALUE)
        );

        editSelected.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        editSelected.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/edit 32.png"))); // NOI18N
        editSelected.setText("تعديل");
        editSelected.setMargin(new java.awt.Insets(2, 2, 2, 2));
        editSelected.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editSelectedActionPerformed(evt);
            }
        });

        deleteselected.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        deleteselected.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/document-delete-icon24.png"))); // NOI18N
        deleteselected.setText("حذف");
        deleteselected.setMargin(new java.awt.Insets(2, 2, 2, 2));
        deleteselected.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteselectedActionPerformed(evt);
            }
        });

        add.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        add.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/Files-New-File-icon 24.png"))); // NOI18N
        add.setText("اضافة");
        add.setMargin(new java.awt.Insets(2, 2, 2, 2));
        add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("قائمة احضارات: ");

        bldlbl1.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        bldlbl1.setForeground(new java.awt.Color(51, 51, 255));
        bldlbl1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("للمحضر");

        bldlbl.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        bldlbl.setForeground(new java.awt.Color(51, 51, 255));
        bldlbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel3.setText("بحث  :");

        searchjTextField1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        searchjTextField1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                searchjTextField1KeyPressed(evt);
            }
        });

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/prev-icon24.png"))); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        add1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        add1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/print-icon 32.png"))); // NOI18N
        add1.setText("طباعة");
        add1.setMargin(new java.awt.Insets(2, 2, 2, 2));
        add1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                add1ActionPerformed(evt);
            }
        });

        jMenu3.setText("احصائيات");

        jMenuItem6.setText("الكميات والكلف");
        jMenuItem6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem6ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem6);

        jMenuItem9.setText("حساب الموردين");
        jMenuItem9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem9ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem9);

        jMenuBar1.add(jMenu3);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(163, 163, 163)
                        .addComponent(bldlbl, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel2)
                        .addGap(16, 16, 16)
                        .addComponent(bldlbl1, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel1)
                        .addGap(0, 157, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(deleteselected)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(editSelected)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(add)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(add1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(searchjTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel3)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel2)
                    .addComponent(bldlbl, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bldlbl1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(editSelected, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(deleteselected, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(add))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(add1, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(searchjTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
        );

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {add, deleteselected, editSelected});

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        invoke.setEnabled(true);
        invoke.toFront();
    }//GEN-LAST:event_formWindowClosed

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
       
            ShowResuls();
         
    }//GEN-LAST:event_formWindowActivated

    private void inputsRecordsjTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_inputsRecordsjTableMouseClicked

    }//GEN-LAST:event_inputsRecordsjTableMouseClicked

    private void inputsRecordsjTableKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_inputsRecordsjTableKeyPressed

    }//GEN-LAST:event_inputsRecordsjTableKeyPressed

    private void inputsRecordsjTableKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_inputsRecordsjTableKeyReleased

    }//GEN-LAST:event_inputsRecordsjTableKeyReleased

    private void editSelectedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editSelectedActionPerformed
        

        try {
            new add_reference(this,bldno,bld_desc,getselectedRecordID(),refrence_type_id,refrence_type_dsec).setVisible(true);
        }catch (SQLException ex) {
                Logger.getLogger(referenciesPaymentsDetails.class.getName()).log(Level.SEVERE, null, ex);
            }
        
    }//GEN-LAST:event_editSelectedActionPerformed
private int getselectedRecordID()
{
    int  selectedRow = inputsRecordsjTable.getSelectedRow();
        if(selectedRow<0)
        {
            //showMessage("يجب تحديد سطر لحذفه",false);
            return 0;
        }
        
        String refereneName = inputsRecordsjTable.getValueAt(selectedRow, 7).toString();
        String s_quantity = inputsRecordsjTable.getValueAt(selectedRow, 6).toString();
        String s_price = inputsRecordsjTable.getValueAt(selectedRow, 4).toString();
        String s_total = inputsRecordsjTable.getValueAt(selectedRow, 3).toString();
        String s_date= inputsRecordsjTable.getValueAt(selectedRow, 2).toString();
        String s_vendor= inputsRecordsjTable.getValueAt(selectedRow, 1).toString();

       
        //if(Functions.deletePrevilege){
            String refer_id = "";
            String vend_id = "";

            try {

                refer_id = conn.searchIdwithcondition("references_", "reference_id", "desc_", refereneName);
                vend_id = conn.searchIdwithcondition("vendors", "vendor_id", "vendor_name", s_vendor);

                String[] values = {
                    "'" + vend_id + "'",
                    "'" + s_quantity + "'",
                    "'" + s_price + "'",
                    "'" + s_total + "'",
                    "'" + s_date + "'",
                    "'" + refer_id + "'",
                    "'" + bldno + "'"};

                String[] fields1 ={"vendor_id", "quantity", "price", "total_price", "date_", "reference_id","buildno"};
                
                return conn.getIDByCondiotonArray(tableName, fields1, values,tableKey);

                
            } catch (SQLException ex) {
               return 0;
            }
}
    private void deleteselectedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteselectedActionPerformed
      
            try {

               
                conn.deleteFromTable(tableName, tableKey, ""+getselectedRecordID());
                ShowResuls();
            } catch (SQLException ex) {
                Logger.getLogger(referenciesPaymentsDetails.class.getName()).log(Level.SEVERE, null, ex);
            }

            
            //deleteselected.setEnabled(false);
    }//GEN-LAST:event_deleteselectedActionPerformed

    private void addActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addActionPerformed

     try {
         new add_reference(this,this.bldno,bld_desc,0,refrence_type_id,refrence_type_dsec).setVisible(true);
     }catch (SQLException ex) {
                Logger.getLogger(referenciesPaymentsDetails.class.getName()).log(Level.SEVERE, null, ex);
            }
 
    }//GEN-LAST:event_addActionPerformed

    private void jMenuItem6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem6ActionPerformed
       try {
         new pricesReport(this,this.bldno,this.bld_desc,this.refrence_type_id,this.refrence_type_dsec).setVisible(true);
     }catch (SQLException ex) {
                Logger.getLogger(referenciesPaymentsDetails.class.getName()).log(Level.SEVERE, null, ex);
            }
    }//GEN-LAST:event_jMenuItem6ActionPerformed

    private void jMenuItem9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem9ActionPerformed
        // TODO add your handling code here:
        
        try {
         new refPaymentReport(this,this.bldno,this.bld_desc,this.refrence_type_id,this.refrence_type_dsec).setVisible(true);
     }catch (SQLException ex) {
                Logger.getLogger(referenciesPaymentsDetails.class.getName()).log(Level.SEVERE, null, ex);
            }
    }//GEN-LAST:event_jMenuItem9ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
             
        String searchtext=searchjTextField1.getText();
        searchTerm=searchjTextField1.getText();
        String whereClause = "and (rec_references.notice like '%" + searchtext + "%'"
        + " or vendors.vendor_name like '%" + searchtext + "%'"
         + " or references_.desc_ like '%" + searchtext + "%')  order by rec_references.date_ DESC";

        try {
            System.out.println(resultquery+whereClause);
            conn.QueryTable(resultquery+whereClause, inputsRecordsjTable);
        }catch (NullPointerException ex) {

        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void add1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_add1ActionPerformed

        Map parameters = new HashMap();

        try {
           
            parameters.put("ref_id", refrence_type_id);
            parameters.put("ref_name", refrence_type_dsec);

            parameters.put("bld_id", new Integer(this.bldno));
            parameters.put("bld_name", this.bld_desc);
            
            parameters.put("search",searchTerm);
          
                

            Functions.printJasperReport(parameters, "referencereport", true);
             
        } catch (NullPointerException ex) {

        } 

    }//GEN-LAST:event_add1ActionPerformed

    private void searchjTextField1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_searchjTextField1KeyPressed
  
    }//GEN-LAST:event_searchjTextField1KeyPressed

 

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton add;
    private javax.swing.JButton add1;
    private javax.swing.JLabel bldlbl;
    private javax.swing.JLabel bldlbl1;
    private javax.swing.JButton deleteselected;
    private javax.swing.JButton editSelected;
    private static javax.swing.JTable inputsRecordsjTable;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JMenuItem jMenuItem9;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField searchjTextField1;
    // End of variables declaration//GEN-END:variables

   
    private void ShowResuls() {
        try {
            System.out.println(resultquery);
            conn.QueryTable(resultquery+" order by rec_references.date_ DESC", inputsRecordsjTable);
        }catch (NullPointerException ex) {
            
        }
            
        
        
       // conn.QueryTable(recordsquery, cardRecordsjTable);
    }
}
